name: dnd_helper
description: Helper for Game Mastering
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shouldly: ^0.5.0+1
  mockito: ^5.4.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
